#!/bin/bash
#
# Program: nparse
# Version: 1.0
# License: MIT
# Author: Benoit DOLEZ <bdolez@ant-computing.com>
# Copyright: 2017-2020
#

# ':' and ',' are denied in credentials
# CREDENTIALS_SEPARATOR='[,:]'

unset LANG
declare PATH=/sbin:/usr/sbin:/bin:/usr/bin:${PATH}
shopt -s extglob

function read-oid-equal-value() {
  local IFS=$' '

  unset VALUE ETHER IPADDR TIMETICKS
  read OID EQUAL ORIGIN || return $?
  # [[ -z $OID ]] && { echo $OID $EQUAL $ORIGIN ; return 255 ; }
  [[ $OID ]] || return 255
  debug -9 "read-oid-equal: $OID = $ORIGIN"
  if [[ ${ORIGIN:0:12} == "Hex-STRING: " ]] ; then
    VALUE="${ORIGIN:11}"
    [[ ${#VALUE} == 12 ]] && { 
      printf -v IPADDR "%d.%d.%d.%d" ${VALUE// / 0x}
    }
    [[ ${#VALUE} == 18 ]] && { 
      ETHER=${VALUE:1} ; ETHER=${ETHER// /:} ; ETHER=${ETHER,,} ;
    }
    printf -v VALUE "${VALUE// /\\x}"
  elif [[ ${ORIGIN:0:9} == "INTEGER: " ]] ; then
    VALUE=${ORIGIN:9}
  elif [[ ${ORIGIN:0:11} == "IpAddress: " ]] ; then
    VALUE=${ORIGIN:11}
  elif [[ ${ORIGIN:0:5} == "OID: " ]] ; then
    VALUE=${ORIGIN:5}
  elif [[ ${ORIGIN} == '""' ]] ; then
    VALUE=""
  elif [[ ${ORIGIN:0:10} == "Timeticks:" ]]; then
    VALUE="${ORIGIN:11}"
    TIMETICKS="${VALUE%%)*}"
    TIMETICKS="${TIMETICKS:1}"
  else
    VALUE="$ORIGIN"
  fi
  return 0
}

function np-cb-snmp-dot1qTpFdbTable-scan() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.17.7.1.2.2.1
  local pidx
  local ether
  local vlan

  while read-oid-equal-value ; do
    case $OID in
      $boid.2.*) {
        vlan=${OID#$boid.2.}; vlan=${vlan%%.*}
        ether=${OID#$boid.2.}; ether=${ether#*.}
        printf -v ether "%02x:%02x:%02x:%02x:%02x:%02x" ${ether//./ }
        pidx=$VALUE
        echo "$target dot1qFdb $ether p$pidx ($vlan)"
      } ;;
    esac
  done
  return 0
}

function np-cb-snmp-cisco-dot1qTpFdbTable-scan() {
  np-cb-snmp-dot1qTpFdbTable-scan "$@"
}

function np-x-snmp-dot1q() {
  np-cb-snmp-dot1qTpFdbTable-scan "$@"
}

function np-cb-snmp-dot1dTpFdbTable-scan() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.17.4.3.1
  local pidx
  local ether

  while read-oid-equal-value ; do
    case $OID in
      $boid.2.*) {
        ether=${OID#$boid.2.}
        printf -v ether "%02x:%02x:%02x:%02x:%02x:%02x" ${ether//./ }
        pidx=$VALUE
        echo "$target dot1dFdb $ether p$pidx"
      } ;;
    esac
  done
  return 0
}

function np-cb-snmp-cisco-dot1dTpFdbTable-scan() {
  np-cb-snmp-dot1dTpFdbTable-scan "$@"
}

function np-x-snmp-dot1d() {
  np-cb-snmp-dot1dTpFdbTable-scan "$@"
}

function to-string() {
  local value=$1; shift
  local values=( "$@" )
  if (( $value < ${#values[@]} )); then
    REPLY="${values[$value]}"
  else
    REPLY="undefined"
  fi
}

function np-cb-snmp-ifTable-scan() {
  np-x-snmp-if "$@"
}

function np-x-snmp-if() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.2.2.1
  local ifgreatestlastchange=0

  declare -A ifname ifmac iflastchange ifadminstatus ifoperstatus

  while read-oid-equal-value ; do
    case $OID in
      $boid.2.*) ifname[${OID#$boid.2.}]=$VALUE ;;
      $boid.6.*) ifmac[${OID#$boid.6.}]=$ETHER ;;
      $boid.7.*) {
        to-string $VALUE undefined up down
        ifadminstatus[${OID#$boid.7.*}]=$REPLY
      } ;;
      $boid.8.*) {
        to-string $VALUE undefined up down
        ifoperstatus[${OID#$boid.8.*}]=$REPLY
      } ;;
      $boid.9.*) {
        (( TIMETICKS/100 > ifgreatestlastchange )) && ifgreatestlastchange=$((TIMETICKS/100))
        iflastchange[${OID#$boid.9.}]=$((TIMETICKS/100))
      } ;;
    esac
  done
  for idx in ${!ifmac[@]} ; do
    echo -n "$target ifname #$idx ${ifname[$idx]:--}"
    echo -n " ${ifmac[$idx]:--}"
    echo -n " ${ifadminstatus[$idx]:--}/${ifoperstatus[$idx]}"
    # if (((ifgreatestlastchange-${iflastchange[$idx]:--}) >= 60*86400)); then 
    #   echo -n " $(((ifgreatestlastchange-${iflastchange[$idx]:--})/(30*86400))) months ago"
    # elif (((ifgreatestlastchange-${iflastchange[$idx]:--}) >= 14*86400)); then 
    #   echo -n " $(((ifgreatestlastchange-${iflastchange[$idx]:--})/(7*86400))) weeks ago"
    # elif (((ifgreatestlastchange-${iflastchange[$idx]:--}) >= 2*86400)); then 
    #   echo -n " $(((ifgreatestlastchange-${iflastchange[$idx]:--})/(1*86400))) days ago"
    # elif (((ifgreatestlastchange-${iflastchange[$idx]:--}) >= 2*3600)); then 
    #   echo -n " $(((ifgreatestlastchange-${iflastchange[$idx]:--})/(1*3600))) hours ago"
    # else
    #   echo -n " $((ifgreatestlastchange-${iflastchange[$idx]:--})) seconds ago"
    # fi
    echo -n " $(((ifgreatestlastchange-${iflastchange[$idx]:--})/86400)) days ago"
    echo
    
  done
  return 0
}

function np-cb-snmp-ifXTable-scan() {
  np-x-snmp-ifX "$@"
}

function np-x-snmp-ifX() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.31.1.1.1

  declare -A ifname ifalias

  while read-oid-equal-value ; do
    case $OID in
      $boid.1.*)  ifname[${OID#$boid.1.}]=$VALUE ;;
      $boid.18.*) ifalias[${OID#$boid.18.}]=$VALUE ;;
    esac
  done
  for idx in ${!ifalias[@]} ; do
    echo "$target ifalias #$idx ${ifname[$idx]:--} ${ifalias[$idx]:--}"
  done
  return 0
}

function np-cb-snmp-ipNetToMediaTable-scan() {
  np-x-snmp-arp "$@"
}

function np-x-snmp-arp() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.4.22.1
  local ifidx
  local ipaddr

  while read-oid-equal-value ; do
    case $OID in
      $boid.2.*.*) {
        ifidx=${OID#$boid.2.}
        ipaddr=${ifidx#*.}
        ifidx=${ifidx%%.*}
        echo "$target arp $ipaddr $ETHER #$ifidx"
      } ;;
    esac
  done
  return 0
}

function np-cb-snmp-dot1dBasePortTable-scan() {
  np-cb-snmp-cisco-fdb "$@"
}

function np-cb-snmp-fdb() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.17.1.4.1
  local ifidx
  local ipaddr

  while read-oid-equal-value ; do
    case $OID in
      $boid.2.*) {
        ifidx=${OID#$boid.2.}
        echo "$target port_ifidx p${OID#$boid.2.} #$VALUE"
      } ;;
    esac
  done
  return 0
}

function np-cb-snmp-cisco-dot1dBasePortTable-scan() {
  np-cb-snmp-dot1dBasePortTable-scan "$@"
}

function np-cb-snmp-ipAddrTable-scan() {
  np-x-snmp-ipAdEnt "$@"
}

function np-x-snmp-ipAdEnt() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.4.20.1

  declare -A mask ifidx

  while read-oid-equal-value ; do
    case $OID in
      $boid.2.*) ifidx[${OID#$boid.*.}]=$VALUE ;;
      $boid.3.*) mask[${OID#$boid.*.}]=$VALUE ;;
    esac
  done
  for ip in ${!ifidx[@]} ; do
    echo "$target ipv4 $ip/${mask[$ip]} #${ifidx[$ip]}"
  done
  return 0
}

function np-cb-snmp-ipRouteTable-scan() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.4.21.1

  declare -A mask ifidx nexthop

  while read-oid-equal-value ; do
    case $OID in
      $boid.2.*) ifidx[${OID#$boid.*.}]=$VALUE ;;
      $boid.7.*) nexthop[${OID#$boid.*.}]=$VALUE ;;
      $boid.11.*) mask[${OID#$boid.*.}]=$VALUE ;;
    esac
  done
  for ip in ${!ifidx[@]} ; do
    echo "$target route $ip/${mask[$ip]} ${nexthop[$ip]} #${ifidx[$ip]}"
  done
  return 0
}

function np-cb-snmp-ipCidrRouteTable-scan() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.4.24.4.1

  declare -A net mask tos nexthop ifidx

  while read-oid-equal-value ; do
    case $OID in
      $boid.1.*) net[${OID#$boid.*.}]=$VALUE ;;
      $boid.2.*) mask[${OID#$boid.*.}]=$VALUE ;;
      $boid.3.*) tos[${OID#$boid.*.}]=$VALUE ;;
      $boid.4.*) nexthop[${OID#$boid.*.}]=$VALUE ;;
      $boid.5.*) ifidx[${OID#$boid.*.}]=$VALUE ;;
    esac
  done
  for id in ${!ifidx[@]} ; do
    if [[ -z ${net[$id]} ]] ; then
      local IFS='.'
      local oids=( $id )
      net[$id]="${oids[*]:0:4}"
      mask[$id]="${oids[*]:4:4}"
      tos[$id]="${oids[*]:8:1}"
      nexthop[$id]="${oids[*]:9:4}"
    fi
    echo "$target route ${net[$id]}/${mask[$id]} ${nexthop[$id]} #${ifidx[$id]}"
  done
  return 0
}


function np-cb-snmp-inetCidrRouteTable-scan() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.4.24.7.1.

  local idx
  declare -A idx

  while read-oid-equal-value ; do
    case $OID in
      $boid.7.*) ;;
      $boid.12.*) ;;
    esac
  done
  for id in ${!ifidx[@]} ; do
    :
  done
  return 0
}

function np-cb-snmp-dot3StatsTable-scan() {
  np-x-snmp-dot3Stats "$@"
}

function np-x-snmp-dot3Stats() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.10.7.2.1

  local idx
  declare -A dot3StatsDuplexStatus

  while read-oid-equal-value ; do
    case $OID in
      $boid.19.*) dot3StatsDuplexStatus[${OID#$boid}]=$VALUE ;;
    esac
  done
  for idx in ${!dot3StatsDuplexStatus[@]} ; do
    : echo "$target dot3StatsTable #$idx ${dot3StatsDuplexStatus[$idx]}"
  done
  return 0
}

function np-cb-snmp-dot1qTpFdbTable-scan-v0() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.17.7.1.2.2.1

  local idx
  declare -A dot1qTpFdbPort

  while read-oid-equal-value ; do
    case $OID in
      $boid.2.*) dot1qTpFdbPort[${OID#$boid.2.}]=$VALUE ;;
    esac
  done
  for idx in ${!dot1qTpFdbPort[@]} ; do
    ether=${idx#*.}
    idx=${idx%.$ether}
    : echo "$target dot1qTpFdbTable S$idx $ether"
  done
  return 0
}

function np-cb-snmp-dot1qVlanStaticTable-scan() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.17.7.1.4.3.1

  local idx
  declare -A dot1qVlanStaticName

  while read-oid-equal-value ; do
    case $OID in
      $boid.1.*) dot1qVlanStaticName[${OID#$boid.1.}]=$VALUE ;;
    esac
  done
  for idx in ${!dot1qVlanStaticName[@]} ; do
    echo "$target dot1qVlanStaticTable V$idx ${dot1qVlanStaticName[$idx]}"
  done
  return 0
}

function np-cb-snmp-dot1qVlanCurrentTable-scan() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.17.7.1.4.2.1

  return 0
}

function np-cb-snmp-dot1qPortVlanTable-scan() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.17.7.1.4.5.1

  return 0
}

function np-cb-snmp-lldpDevice-scan() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.0.8802.1.1.2.1.3
  
  local lldpLocSysName
  
  while read-oid-equal-value ; do
    case $OID in
      $boid.3.0) lldpLocSysName=$VALUE ;;
    esac
  done

  echo "$target lldpLocSysName $lldpLocSysName"

  return 0
}

function np-cb-snmp-lldpLocPortTable-scan() {
  np-x-snmp-lldpLoc "$@"
}

function np-x-snmp-lldpLoc() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.0.8802.1.1.2.1.3.7.1

  local idx
  declare -A lldpLocPortIdSubtype

  while read-oid-equal-value ; do
    case $OID in
      $boid.2.*) lldpLocPortIdSubtype[${OID#$boid.2.}]=$VALUE ;;
      $boid.3.*) lldpLocPortId[${OID#$boid.3.}]=$VALUE ;;
      $boid.4.*) lldpLocPortDesc[${OID#$boid.4.}]=$VALUE ;;
    esac
  done
  for idx in ${!lldpLocPortTable[@]} ; do
    :
  done
  return 0
}

function np-cb-snmp-lldpRemTable-scan() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=

  return 0
}

function np-cb-snmp-lldpRemPortTable-scan() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=

  return 0
}

function np-cb-snmp-dot3adAggPortTable-scan() {
  np-x-snmp-dot3adAgg "$@"
}

function np-x-snmp-dot3adAgg() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.2.840.10006.300.43.1.2.1.1
  local IFS=','
  
  declare -A dot3adAggPortSelectedAggID
  
  while read-oid-equal-value ; do
    case $OID in
      $boid.12.*) dot3adAggPortSelectedAggID[$VALUE]=$IFS${OID#$boid.12.} >&2 ;;
    esac
  done
  
  for idx in ${!dot3adAggPortSelectedAggID[@]} ; do
    echo $target dot3adAggPortSelectedAggID #$idx${dot3adAggPortSelectedAggID[$idx]//$IFS/ }"
  done


  return 0
}

function np-cb-snmp-check-cisco() {
  return 0
}

function np-cb-snmp-cisco-vtpVlanTable-scan() {
  return 0
}

function np-cb-snmp-cisco-vlanTrunkPortTable-scan() {
  return 0
}

function np-cb-snmp-cisco-vmTable-scan() {
  return 0
}

function np-cb-snmp-cisco-pagpGroupTable-scan() {
  return 0

}

function np-cb-snmp-cisco-stackTable-scan() {
  return 0

}

function np-cb-snmp-cisco-cdpDevice-scan() {
  return 0
}

function np-cb-snmp-cisco-cdpTable-scan() {
  np-x-snmp-cdpCache "$@"
}
 
function np-x-snmp-cdpCache() { 
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.4.1.9.9.23.1.2.1.1
  
  declare -A cdpCacheAddress cdpCacheDeviceId cdpCacheDevicePort
  declare -A cdpCacheCapabilities cdpCachePlatform cdpCacheNativeVLAN
  
  while read-oid-equal-value ; do
    case $OID in
      $boid.4.*) cdpCacheAddress[${OID#$boid.*.}]=${IPADDR:-${ETHER:-$VALUE}} ;;
      $boid.6.*) cdpCacheDeviceId[${OID#$boid.*.}]=$VALUE ;;
      $boid.7.*) cdpCacheDevicePort[${OID#$boid.*.}]=$VALUE ;;
      $boid.8.*) cdpCachePlatform[${OID#$boid.*.}]=$VALUE ;;
      $boid.9.*) cdpCacheCapabilities[${OID#$boid.*.}]=$VALUE ;;
      $boid.11.*) cdpCacheNativeVLAN[${OID#$boid.*.}]=$VALUE ;;
    esac
  done

  for idx in ${!cdpCacheAddress[@]} ; do
    ifidx=${idx%.*}
    devidx=${idx#.*}
    printf "$target cdp #$ifidx %s %s %s\n" \
      "${cdpCacheDeviceId[$idx]:--}" \
      "${cdpCacheAddress[$idx]:--}" \
      "${cdpCachePlatform[$idx]:--}"
  done

  return 0
}

function np-cb-snmp-cisco-vtpManagementDomainTable-scan() {
  return 0
}

function np-cb-snmp-cisco-fdb() {
  return 0
}

function np-x-snmp-cdpGlobal() {
  return 0
}

function np-x-snmp-stackPort() {
  return 0
}

function np-x-snmp-pagpGroup() {
  return 0
}

function np-x-snmp-vm() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.4.1.9.9.68.1.2.2.1
  
  declare -A vmVlan
  
  while read-oid-equal-value ; do
    case $OID in
      $boid.2.*) vmVlan[${OID#$boid.*.}]=$VALUE ;;
    esac
  done

  for idx in ${!vmVlan[@]} ; do
    printf "$target pvlan #$idx %s\n" "${vmVlan[$idx]}"
  done

  return 0
}

function np-x-snmp-vlanTrunkPort() {
  return 0
}

function np-x-snmp-vtp() {
  return 0
}

function np-x-snmp-netDefaultGateway() {
  return 0
}

function np-x-snmp-cisco-check-sb() {
  return 0
}

function np-x-snmp-lldpRem() {
  return 0
}

function np-cb-snmp-cisco-vlanTable-scan() {
  return 0
}

function np-cb-check-scan-allowed() {
  return 0
}

function np-cb-resolve() {
  return 0
}

function np-x-snmp-sys() {
  np-cb-snmp-system-scan "$@"
}

function np-cb-snmp-system-scan() {
  local snmp=$1 ; shift
  local target=$1 ; shift
  local boid=.1.3.6.1.2.1.1

  local sysDescr sysObjectID sysContact sysName sysLocation

  while read-oid-equal-value ; do
    case $OID in
      $boid.1.0) sysDescr=${VALUE//[^$'\x20'-$'\x79']/.} ;;
      $boid.2.0) sysObjectID=$VALUE ;;
      $boid.3.0) sysUptime=$TIMETICKS ;;
      $boid.4.0) sysContact=$VALUE ;;
      $boid.5.0) sysName=$VALUE ;;
      $boid.6.0) sysLocation=$VALUE ;;
    esac
  done

  echo "$target sys-type $sysDescr"
  echo "$target sys-name $sysName"
  [[ $sysLocation ]] && echo "$target sys-location $sysLocation"
  [[ $sysContact ]] && echo "$target sys-contact $sysContact"
  [[ $sysUptime ]] && echo "$target sys-uptime $sysUptime"

  return 0
}


function np-cb-find-credential() {
  local source=$1 ; shift
  local origin=$1 ; shift
  local ctype=$1 ; shift
  local version
  local community

  if [[ $ctype == snmp ]]; then
    read LINE; version=${LINE#* = }
    read LINE; community=${LINE#* = }
    echo "$origin cred snmp $version $community"
  fi

  return 0
}

function np-cb-credential-snmp() {
  local source=$1 ; shift
  local origin=$1 ; shift
  local line

  while read line && [[ $line != "" ]] ; do
    echo "$origin cred $line"
  done
}

function np-cb-credential-ssh-linux() {
  local source=$1 ; shift
  local origin=$1 ; shift
  local line
  
  while read line && [[ $line != "" ]] ; do
    echo "$origin cred $line"
  done
}

function np-cb-snmp-scan() {
  if [[ ${3#.1.3.6.1.2.1.2.2.1.*} ]]; then
    np-cb-snmp-ifTable-scan "$@" && return
  fi

  while read-oid-equal-value ; do
    :
  done
}

function np-iproute2-ip-address() {
  local source=$1 ; shift
  local origin=$1 ; shift
  local IFS=$'\r '
  local PATTERN2="([0-9]+): ([0-9a-zA-Z_@.]+): <([^>]*)> (.*)"
  local ether ipv4 ifid ifname ifstate

  while read ; do
    if [[ ${REPLY} =~ $PATTERN2 ]] ; then
      ifid=${BASH_REMATCH[1]}
      ifname=${BASH_REMATCH[2]}
      ifstate=${BASH_REMATCH[3]}
      set -- ${BASH_REMATCH[4]}
    else
      set -- $REPLY
    fi

    [[ $# -gt 2 ]] || break

    while (( $# > 0 )) ; do
      case $1 in
        mtu) shift ;;
        qdisc) shift ;;
        state) shift ;;
        group) shift ;;
        qlen) shift ;;
        valid_lft) shift ;;
        preferred_lft) shift ;;
        link/ipip) shift ;;
        link/loopback) shift ;;
        link/ether) ether=$2 ; shift ;;
        inet) ipv4=$2 ; shift ;;
        inet6) shift ;;
        brd) shift ;;
        scope) shift ; shift ;;
        *) warning "ip-address unknown option '$1'" ;;
      esac
      shift
    done

    [[ $ether ]] && {
      echo "$source:$origin ether $ether $ifname"
      unset ether
    }
    [[ $inet ]] && {
      echo "$source:$origin ipv4 $ipv4 $ifname"
      unset ipv4
    }
  done
}

function np-iproute2-ip-route() {
  local source=$1 ; shift
  local origin=$1 ; shift
  local IFS=$'\r '
  local gw ifname net

  while read ; do
    set -- ${REPLY}
    net=$1 ; shift
    [[ $# -gt 2 ]] || break
    while (( $# > 0 )) ; do
      case $1 in
        via) gw=$2 ; shift ;;
        dev) ifname=$2 ; shift ;;
        proto) shift ;;
        src) shift ;;
        scope) shift ;;
        *) warning "ip-route unknown option <$1>" ;;
      esac
      shift
    done
    echo "$source:$origin route $net $gw $ifname"
  done
}

function np-iproute2-ip-neigh() {
  local source=$1 ; shift
  local origin=$1 ; shift
  local IFS=$'\r '
  local addr ether ifname

  while read ; do
    unset ether addr ifname
    set -- ${REPLY}
    addr=$1 ; shift
    [[ $# -gt 2 ]] || break
    while (( $# > 0 )) ; do
      case $1 in
        dev) ifname=$2 ; shift ;;
        lladdr) ether=$2 ; shift ;;
        STALE) shift ;;
        FAILED) shift ;;
        REACHABLE) shift ;;
        DELAY) shift ;;
        *) warning "ip-neigh unknown option <$1>" ;;
      esac
      shift
    done
    [[ $ether ]] && echo "$source:$origin arp $ether $addr $ifname"
  done
}

function np-iproute2() {
  local IFS=' '
  while read ; do
    if [[ $REPLY =~ "ip a" ]] ; then
      np-iproute2-ip-address "$@"
    elif [[ $REPLY =~ "ip ro" ]] ; then
      np-iproute2-ip-route "$@"
    elif [[ $REPLY =~ "ip n" ]] ; then
      np-iproute2-ip-neigh "$@"
    fi
  done
}

function np-winexe-getline() {
  local command=$1
  read REPLY
  [[ $command == hostname ]] && origin=$REPLY 
  echo "$origin $command $origin"
  return 0
}

function np-winexe-getblock() {
  local command=$1
  local block
  
  while read LINE; do
    if [[ ${LINE:0:4} == "==> " ]]; then
      echo "$origin block[${command%% *}] ${block%\\n}"
      NP_WINEXE_CONTINUE=1
      return 0
    fi
    block="$block${LINE%$'\r'}\\n"
  done
  echo "$origin block[${command%% *}] ${block%\\n}"
  return 0
}

function np-winexe-xml() {
  local command=$1
  while read LINE; do
    if [[ ${LINE:0:4} == "==> " ]]; then
      NP_WINEXE_CONTINUE=1
      return 0
    fi
  done
  return 0
}

function np-winexe-getlist() {
  local command=$1
  local IFS=$'\t'
  local key skey spcs attr
  read LINE ; while [[ ${LINE%$'\r'} == "" ]]; do read LINE; done
  while [[ $? == 0 ]] ; do
    LINE=${LINE%$'\r'}
    if [[ ${LINE} == "" ]]; then
      break
    elif [[ ${LINE} =~ ^([^ ][^:]*)\ *:\ +(.*)$ ]]; then
      # Attribut: Value
      spcs=0
      key[spcs]="k[$command].k[${BASH_REMATCH[1]%%*( )}]"
      echo "$origin ${key[spcs]}._value ${BASH_REMATCH[2]}"
    elif [[ ${LINE} =~ ^([\ ]+)\[([0-9]+)\][^:]*:\ +(.*)$ ]]; then
      # <space>[xx]: Value
      (( ${#BASH_REMATCH[1]}+1 <= spcs )) && key[spcs]=${key[${#BASH_REMATCH[1]}+1]%.k\[*}
      key[${#BASH_REMATCH[1]}+1]="${key[spcs]}.k[${BASH_REMATCH[3]%%*( )}]"
      ((spcs=${#BASH_REMATCH[1]}+1))
      echo "$origin ${key[spcs]}._id ${BASH_REMATCH[2]}"
    elif [[ ${LINE} =~ ^([\ ]+)([^:]*)\ *:\ +([^:]*)$ ]] ; then
      # <space>Attribut: Value
      (( ${#BASH_REMATCH[1]} <= spcs )) && key[spcs]=${key[${#BASH_REMATCH[1]}]%.k\[*}
      key[${#BASH_REMATCH[1]}]="${key[spcs]}.k[${BASH_REMATCH[2]%%*( )}]"
      spcs=${#BASH_REMATCH[1]}
      echo "$origin ${key[spcs]}._value = ${BASH_REMATCH[3]}"
    elif [[ ${LINE} =~ ^([\ ]+)([^:]*)$ ]] ; then
      # <space>Attribut (start of array)
      (( ${#BASH_REMATCH[1]} <= spcs )) && key[spcs]=${key[${#BASH_REMATCH[1]}]%.k\[*}
      key[${#BASH_REMATCH[1]}]="${key[spcs]}.k[${BASH_REMATCH[2]%%*( )}]"
      spcs=${#BASH_REMATCH[1]}
    fi
    read LINE
  done
}

# 123456789012345678901234567890
# ABC     DEF        GHI 
#  b[1] = 4
#  b[2] = 8
#  b[3] = 12
#  b[4] = 16
#  b[5] = 19
#  b[6] = 23


function auto-create-fixed-columns-parser() {
  awk -v FS='' '
  {
    if (NR == 1) h = $0;
    for (i = 1 ; i < NF ; i++) {
      if (NR == 1)
        a[i]=" ";
      else if ($i != " ")
        delete a[i];
    }
    a[i+1] = " ";
  }
  END {
    printf("function fixed-columns-parser(){\n");
    printf(" local a=()\n");
    printf(" local IFS=$\"\t\"\n");
    printf(" while read; do\n");
    printf("  a=(\n");
    i = 1;
    for (j in a) b[i++] = j;
    j = 0;
    for (i = 1 ; b[i] ; i++) {
      # merge field with empty header
      if (match(substr(h, b[i], b[i+1]-b[i]), "^ +$")) continue;
      printf("   \"${REPLY:%d:%d}\"\n", j, b[i]-j-1);
      j = b[i];
    }
    printf("  )\n");
    printf("  a=( \"${a[@]##*( )}\" )\n");
    printf("  echo \"${a[*]%%%%*( )}\"\n");
    printf(" done\n");
    printf("}\n");
  }
  '
}

function gettsv2something() {
  local IFS=$'\t'
  local headers
  read LINE
  headers=( $LINE )
  read LINE || return 1
  while [[ "${LINE:0:1}" != "-" ]]; do
    local headers_next=( $LINE )
    for ((i = 0 ; i < ${#headers[@]} ; i++)); do
      headers[i]="${headers[i]}${headers_next[i]}"
    done
    read LINE || return 1
  done
  while read LINE; do
    cols=( $LINE )
    for ((i = 0 ; i < ${#headers[@]} ; i++)); do
      echo "$origin k[${command%% *}].k[${cols[0]}].${headers[i]}=${cols[i]}"
    done
  done
}

function np-winexe-getarray() {
  local command=$1
  local IFS=$'\t'
  local lines=( )

  read LINE ; while [[ ${#LINE} -le 1 ]]; do read LINE; done
  while [[ $? == 0 ]] && [[ ${#LINE} -gt 1 ]] ; do
    LINE=${LINE%$'\r'}
    lines+=( "$LINE" )
    read LINE
  done
  output="$(IFS=$'\n';echo "${lines[*]}"|iconv -f UTF8 -t ISO8859-1//TRANSLIT)"
  eval "$(auto-create-fixed-columns-parser <<< "${output}")"
  fixed-columns-parser <<<"${output}" |
    gettsv2something
}

function np-winexe() {
  local IFS=' '
  local command=( $1 ); shift
  if [[ ${command[0]} == "hostname" ]]; then
    np-winexe-getline && origin=${REPLY%$'\r'}
  elif [[ ${command[0]} == "systeminfo" ]]; then
    np-winexe-getlist ${command[0]}
  elif [[ ${command[0]:0:4} == "gwmi" ]]; then
    np-winexe-getlist ${command[3]}
  elif [[ ${command[0]:0:13} == "Get-GPOReport" ]]; then
    np-winexe-xml ${command[0]}
  elif [[ ${command[0]:0:4} == "Get-WmiObject" ]]; then
    np-winexe-getarray ${command[2]}
  elif [[ ${command[0]:0:4} == "Get-" ]]; then
    np-winexe-getarray ${command[0]}
  else
    np-winexe-getblock ${command[0]}
  fi
}

function np-cb-ipv4-fping() {
  local source=$1 ; shift
  local origin=$1 ; shift

  # read LINE || return 1
  while [[ ${#LINE} -gt 0 ]]; do
    if [[ $LINE =~ "is alive" ]]; then
      echo "$origin ipv4 ${LINE%% *}"
    fi
    read LINE
  done
}

function nparse-generic() {
  local PATTERN1="<<<< ([^\ ]+)\ ?(.*) >>>>"
  local PATTERN2="^==> ([^:]+) :"
  local LINE
  # read first line
  read LINE
  # while read in loop
  while [[ $? == 0 ]] ; do
    if [[ $LINE =~ $PATTERN1 ]] ; then
      debug -7 "Found header '$LINE'"
      if declare -F np-${BASH_REMATCH[1]} >/dev/null ; then
        debug -5 "Parse ${BASH_REMATCH[2]} with np-${BASH_REMATCH[1]}"
        np-${BASH_REMATCH[1]} ${BASH_REMATCH[2]}
      else
        debug -3 "Parse ${BASH_REMATCH[2]} : undefine parser ${BASH_REMATCH[1]}"
      fi
    elif [[ $LINE =~ $PATTERN2 ]] ; then
      debug -7 "Found header '$LINE'"
      np-winexe "${BASH_REMATCH[1]%$'\r'}"
      (( $NP_WINEXE_CONTINUE )) && {
        NP_WINEXE_CONTINUE=0
        continue
      }
    fi
    # read new line
    read LINE
  done
  return 0
}

function my_cat() {
  if [[ -z ${1##*.gz} ]] ; then
    zcat "$1"
  elif [[ -z ${1##*.xz} ]] ; then
    xzcat "$1"
  else
    cat "$1"
  fi
}

function version() {
  while read COMMENT ATTRIBUT VALUE; do
    [[ "${COMMENT:0:1}" == "#" ]] || break
    case "$ATTRIBUT" in
      "Program:")   PROGRAM=$VALUE ;;
      "Version:")   VERSION=$VALUE ;;
      "License:")   LICENSE=$VALUE ;;
      "Author:")    AUTHOR=$VALUE ;;
      "Copyright:") COPYRIGHT=$VALUE ;;
    esac
  done < $0
  echo "${0##*/} $VERSION - Copyright $COPYRIGHT, $AUTHOR"
  echo "License $LICENSE"
}

function usage() {
  local IFS=$'\t'
  if [[ $0 == "-bash" ]] ; then return 1 ; fi
  [[ $# -gt 0 ]] && echo "ERROR: $*" >&2
  version >&2
  echo "Usage: ${0##*/} [options] HOST ..." >&2
  echo "Options:" >&2
  sed -nr "s/^[[:space:]]*## ([^:]*): /\1\t/p" -- "$0" |
    while read OPT DESC ; do
      printf " %-20s %s\n" "$OPT" "$DESC" >&2
    done
  return 0
}

function debug() {
  if [[ ${1:0:1} == "-" ]] ; then
    (( ${1:1} > VERBOSE )) && return
    shift
  fi
  echo "[DEBUG] $* (${FUNCNAME[1]}:${BASH_SOURCE[1]##*/}:${BASH_LINENO[0]})" >&2

}

function warning() {
  echo "WARNING: $*" >&2
}

function fatal() {
  echo "FATAL: $*" >&2
  exit 1
}

function onEXIT() {
  local EXITCODE=$?
  return $EXITCODE
}

declare QUIET=${QUIET:-1}
declare VERBOSE=${VERBOSE:-0}

while (( $# > 0 )); do
  case "$1" in
    ## -h, --help: This help
    -h|--help) usage && exit 0 ;;
    ## -V, --version: Show version
    -V|--version) version && exit 0 ;;
    ## --x-debug: Enable bash debug mode
    --x-debug)    XDEBUG=1 ;;
    ## -v, --verbose: increase verbose level
    -v|--verbose) ((VERBOSE++)) ;;
    --) shift ; break ;;
    -*) usage "Unknown parameter '$1'" && exit 1 ;;
    *) ARGS+=( "$1" ) ;;
  esac
  shift
done

[[ $XDEBUG == 1 ]] && set -x
(( $VERBOSE < 3 )) && function debug() { return $? ; }

# Make VERBOSE&QUIET inverted variables
(( VERBOSE == 0 )) && { QUIET=1 ; unset VERBOSE ; } || unset QUIET

trap onEXIT EXIT

[[ ${#ARGS[@]} == 0 ]] && ARGS=( /dev/stdin )

for input in "${ARGS[@]}" ; do
  if [[ ${input:0:1} == ":" ]] ; then
    # input form is ':parser:filename'
    IFS=":" read empty nparser input <<<"$input"
    my_cat "$input" | np-$nparser file $input
  else
    my_cat "$input" | nparse-generic
  fi
done
