#!/bin/bash
#
# License: MIT License
# Author: Benoit DOLEZ <bdolez@zenetys.com>
# Copyright: 2020
# Version: 1.0
#

# filename usage to determine action
# zpki create-ca "CA-SUBJ"
# zpki create-key "SUBJ"
# zpki create-csr "SUBJ"
# zpki create-crt "SUBJ"

# directory tree :
# .zpki             : ZPKI managed directory
# ca.crt            : CA Certificate
# ca.cnf            : Config for CAb
# ca.key            : CA Private Key
# keys/SUBJ.key     : SUBJ CommonName Private Key
# certs/SUBJ.crt    : SUBJ CommonName Certificate
# requests/SUBJ.csr : SUBJ CommonName Certificate Request

NUMBITS=${ZPKI_NUMBITS:-4096}
NUMDAYS=${ZPKI_NUMDAYS:-366}
CIPHER=${ZPKI_CIPHER:-aes256}
DIGEST=${ZPKI_DIGEST:-sha256}

DEFAULT_CONFIG="
# look at :
# https://www.openssl.org/docs/manmaster/man5/x509v3_config.html

[ ca ]
default_ca             = default_ca_section

[ default_ca_section ]
dir                    = .
certs                  = \$dir/certs
new_certs_dir          = \$dir/certs.new
crl_dir                = \$dir/crl
database               = \$dir/ca.idx
certificate            = \$dir/ca.crt
serial                 = \$dir/ca.srl
crlnumber              = \$dir/ca.crlnum
crl                    = \$dir/ca.crl
private_key            = \$dir/ca.key

copy_extensions        = copy

default_days           = ${NUMDAYS}
default_crl_days       = 30
default_md             = ${DIGEST}
preserve               = no

policy                 = policy_match

[ policy_match ]
countryName             = optional
stateOrProvinceName     = optional
organizationName        = optional
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional


[ req ]
default_bits           = ${NUMBITS}
default_md             = ${DIGEST}
distinguished_name     = distinguished_name

[ x509 ]
x509_extensions        = x509v3_ext

[ crl ]
authorityKeyIdentifier = keyid:always

[ distinguished_name ]
countryName            = Country Name
localityName           = Locality Name (eg, city)
0.organizationName     = Organization Name (eg, company)
organizationalUnitName = Organizational Unit Name (eg, section)
commonName             = Common Name
emailAddress           = Email Address

[ ca_ext ]
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints       = critical,CA:true
keyUsage               = cRLSign, keyCertSign
# subjectAltName         = email:copy
# issuerAltName          = issuer:copy

[ x509v3_ext ]
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid,issuer
basicConstraints       = CA:false
# nsCertType             = @nsCertType_section
# keyUsage               = @keyUsage_section
# extendedKeyUsage       = @extendedKeyUsage_section
# subjectAltName         = email:copy
# issuerAltName          = issuer:copy

[ nsCertType_section ]
# client            = true
# server            = true
# email             = true
# objsign           = true
# reserved          = true
# sslCA             = true
# emailCA           = true
# objCA             = true

[ keyUsage_section ]
# digitalSignature = true
# nonRepudiation   = true
# keyEncipherment  = true
# dataEncipherment = true
# keyAgreement     = true
# keyCertSign      = true
# cRLSign          = true
# encipherOnly     = true
# decipherOnly     = true

[ extentedKeyUsage_section ]
# serverAuth       = true    # SSL/TLS Web Server Authentication.
# clientAuth       = true    # SSL/TLS Web Client Authentication.
# codeSigning      = true    # Code signing.
# emailProtection  = true    # E-mail Protection (S/MIME).
# timeStamping     = true    # Trusted Timestamping
# OCSPSigning      = true    # OCSP Signing
# ipsecIKE         = true    # ipsec Internet Key Exchange
# msCodeInd        = true    # Microsoft Individual Code Signing (authenticode)
# msCodeCom        = true    # Microsoft Commercial Code Signing (authenticode)
# msCTLSign        = true    # Microsoft Trust List Signing
# msEFS            = true    # Microsoft Encrypted File System
"

if tty -s >/dev/null 2>&1; then
    declare -A C=(
        [info]=$'\x1b[1m'
        [warning]=$'\x1b[7;33m'
        [error]=$'\x1b[7;91m'
        [fatal]=$'\x1b[7;1;91m'
        [blue]=$'\x1b[7;34m'
        [reset]=$'\x1b[m'
    )
    HAS_TTY=1
else
    declare -A C=()
    HAS_TTY=
fi

function info() {
    local i;
    local l=info
    [[ ${1:0:2} == -- ]] && l=${1:2} && shift
    for i in "$@"; do
        printf '%s: %s\n' "${C[$l]}${l^^}${C[reset]}" "$i";
    done
}

function fatal() {
    local usage=0
    [[ $1 == --usage ]] && usage=1 && shift
    info --${FUNCNAME[0]} "$@"
    (( $usage )) && usage
    exit 127
}

function error() {
    info --${FUNCNAME[0]} "$@"
}

function warning() {
    info --${FUNCNAME[0]} "$@"
}

function debug() {
    (( DEBUG == 0 )) && return 0
    info --${FUNCNAME[0]} "$@"
}

function yesno() {
  local QUESTION="$1" ; shift
  [[ $YES == 1 ]] && return 0
  while : ; do
    echo -n "$QUESTION (yes/[N]o): " && read
    case $REPLY in
      [Yy]|[Yy][Ee]|[Yy][Ee][Ss]) return 0 ;;
      [Nn]|[Nn][Oo]) return 1 ;;
      *) echo "Bad answer, try again" ;;
    esac
  done
  return 0
}

function echo_quoted() {
  local s=$1 ; shift

  echo -n "${PREFIX:+$PREFIX }"
  # A..Z a..z 0..9 + - , . / =
  [[ $s && -z ${s//[A-Za-z+-9=_]} ]] && echo -n "$s" || echo -n " '${s}'"
  for s in "$@"; do
    [[ $s && -z ${s//[A-Za-z+-9=_]} ]] && echo -n " $s" || echo -n " '${s}'"
  done
  echo
}

function openssl_debug() {
  local IFS=$'\n'
  (( VERBOSE >= 1 )) && PREFIX=": openssl" echo_quoted "$@" >&2
  ERRMSG=( $(openssl "$@" 2>&1) )
  return $?
}

function is-exists() {
  local FORCE
  [[ ${1:0:1} == - ]] && FORCE=${1:1} && shift
  if [[ -s $1 && ! ${FORCE} ]] ; then
    (( VERBOSE >= 1 )) && echo "$1: already exists, bypass" >&2
    return 0
  fi
  return 1
}

function is-error() {
  local ERR=$?
  [[ ${1:0:1} == - ]] && ERR=${1:1} && shift
  [[ $ERR == 0 ]] && return 0
  echo -n "ERROR: $1" >&2
  echo "${ERRMSG[*]/#/$'\n'> }" >&2
  return $ERR
}

#X-ACTION create-cnf: create default openssl config file
function create-cnf() {
  local CNFFILE=${1:-$CNFFILE}
  [[ $FORCE ]] && FORCE_CREATE_CNF=1 && unset FORCE
  is-exists -$FORCE_CREATE_CNF "$CNFFILE" && return 0
  yesno "create config '$CNFFILE' ?" || return
  touch "$CNFFILE"
  is-error "can't create config '$CNFFILE'" || return
  echo "$DEFAULT_CONFIG" >> $CNFFILE
  return 0
}

#X-ACTION create-key [CN|SUBJ]: create key file
function create-key() {
  local KEYFILE=${1:-$KEYFILE}
  [[ $FORCE ]] && FORCE_CREATE_KEY=1 && unset FORCE
  is-exists -$FORCE_CREATE_KEY "$KEYFILE" && return 0
  yesno "create key '$KEYFILE' ?" || return
  PARAMS=(
    -out "$KEYFILE"
    ${CIPHER:+-$CIPHER}
    ${PASSWORD:+-passout env:PASSWORD}
    $NUMBITS
  )
  $OPENSSL genrsa "${PARAMS[@]}"
  is-error "can't create key '$KEYFILE'" || return
}

#X-ACTION create-csr CN|SUBJ [ALTNAMES...]: create request
function create-csr() {
  local CSRFILE=${1:-$CSRFILE}
  [[ $FORCE ]] && FORCE_CREATE_CSR=1 && unset FORCE
  is-exists -$FORCE_CREATE_CSR "$CSRFILE" && return 0
  yesno "create certificate request '$CSRFILE' ?" || return
  create-key "$KEYFILE" || return
  PARAMS=(
    -batch
    -new
    -out "$CSRFILE"
    -key "$KEYFILE"
    ${SUBJECT:+-subj "$SUBJECT"}
    ${SUBJALT:+-addext "subjectAltName=$SUBJALT"}
    ${PASSWORD:+-passin env:PASSWORD}
  )
  $OPENSSL req "${PARAMS[@]}"
  is-error "can't create certificate request '$CSRFILE'" || return
}

#X-ACTION create-self CN|SUBJ [ALTNAMES...]: create self signed certificate
function create-self() {
  local CRTFILE=${1:-$CRTFILE}
  [[ $SUBJECT ]] || fatal "can't get create CA with empty subject"
  [[ $FORCE ]] && FORCE_CREATE_CRT=1 && unset FORCE
  is-exists -$FORCE_CREATE_CRT $CRTFILE && return 0
  yesno "create self-signed certificate '$SUBJECT' ($CRTFILE)?" || return
  create-cnf "$CNFFILE" || return
  create-key "$KEYFILE" || return
  PARAMS=(
    -batch
    -new -x509
    -days "$NUMDAYS"
    -out "$CRTFILE"
    -key "$KEYFILE"
    ${SUBJECT:+-subj "$SUBJECT"}
    ${SUBJALT:+-addext "subjectAltName=$SUBJALT"}
    -config "$CNFFILE" -extensions ${EXT:-x509v3_ext}
    ${PASSWORD:+-passin env:PASSWORD}
  )
  $OPENSSL req "${PARAMS[@]}"
  is-error "can't create auto-signed '$CRTFILE'" || return
}

#X-ACTION create-ca CN|SUBJ: create certificat authority & storage
function create-ca() {
  local CNFFILE=$CA_CNFFILE
  local KEYFILE=$CA_KEYFILE
  local CRTFILE=$CA_CRTFILE
  local SUBJALT # empty
  local FORCE_CREATE_CRT # empty
  local SERIAL=$RANDOM$RANDOM$RANDOM

  create-cnf  "$CNFFILE" || return
  PASSWORD=$CA_PASSWORD create-key "$KEYFILE" || return
  PASSWORD=$CA_PASSWORD EXT="ca_ext" create-self "$CRTFILE" || return
  [[ -d certs ]]      || mkdir certs
  [[ -d certs.new ]]  || mkdir certs.new
  [[ -d crl ]]        || mkdir crl
  [[ -d private ]]    || mkdir private
  [[ -e ca.idx ]]     || touch ca.idx
  [[ -s ca.srl ]]     || printf "%016X\n" $SERIAL > ca.srl
  [[ -s ca.crlnum ]]  || echo 01 > ca.crlnum
  [[ -e .zpki ]]      || touch .zpki
  return 0
}

function create-cert() {
  create-crt "$@"
}

#X-ACTION create-crt {CN|SUBJ} [ALTNAMES...]: create certificate
function create-crt() {
  local CRTFILE=${1:-$CRTFILE}
  [[ $SUBJECT ]] || fatal "can't get create cert with empty subject"
  [[ $FORCE ]] && FORCE_CREATE_CRT=1 && unset FORCE
  is-exists -$FORCE_CREATE_CRT "$CRTFILE" && return 0
  yesno "create certificate '$SUBJECT' ($CRTFILE) ?" || return
  create-csr "$CSRFILE" || return
  PARAMS=(
    -config "$CA_CNFFILE"
    -batch
    -in  "$CSRFILE"
    -out "$CRTFILE"
    -days "$NUMDAYS"
    -extensions ${EXT:-x509v3_ext}
    ${CA_PASSWORD:+-passin env:CA_PASSWORD}
  )
  $OPENSSL ca "${PARAMS[@]}"
  is-error "can't sign request '$CSRFILE' to '$CRTFILE'" || return
  ca-update-db "$CRTFILE" >> ca.idz
}

function ca-update-db() {
  if [[ $1 ]]; then
    local CRTFILE=$1
    local IFS=$'\n'
    local hash serial notBefore notAfter subject issuer email
    for A in hash=$(openssl x509 -in "$CRTFILE" -noout -hash -serial \
                        -startdate -enddate -email -subject -issuer); do
      eval "${A%%=*}='${A#*=}'"
    done
    subject="/${subject//, /\/}"; subject="${subject// = /=}"
    issuer="/${issuer//, /\/}"; issuer="${issuer// = /=}"
    printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\n" "$serial" "$hash" \
         $(date -Iseconds -d "$notBefore") $(date -Iseconds -d "$notAfter") \
         "$subject" "$issuer" "$email"
    return
  fi

  $OPENSSL ca -config "$CA_CNFFILE" -updatedb
  rm ca.idz.new
  find certs.new -maxdepth 1 -type f -name "*.pem" | while read -r; do
    ca-update-db "$REPLY" >> ca.idz.new
  done
  mv -f ca.idz.new ca.idz
}

#X-ACTION ca-list: list certificates store in CA
function ca-list() {
  local CA_IDXFILE=ca.idx
  awk < $CA_IDXFILE '
  BEGIN {
    FS="\t";
    printf("[");
  }
  function rfc3339(date) {
    ds = gensub("(..)", "\\1 ", "g", date)
    return (strftime("%Y-%m-%dT%H:%M:%S%z", mktime("20" ds)));
  }
  {
    printf("%s\n {",((NR==1)?"":","));
    printf("\"status\":\"%s\"",$1);
    printf(",\"expiration\":\"%s\"", rfc3339($2));
    if ($3) printf(",\"revocation\":\"%s\"", rfc3339($3));
    printf(",\"serial\":\"%s\"", $4);
    # printf(",\"filename\":\"%s\"", $5);
    printf(",\"subject\":\"%s\"", $6);
    printf("}");
  }
  END {
    printf("\n]\n");
  }
  '
}

#X-ACTION ca-sign-csr CN|SUBJ|CSRFILE: sign request given in file using CA
function ca-sign-csr() {
  local CSRFILE=${1:-$CSRFILE}
  local CRTFILE=${CRTFILE:-${CSRFILE%.csr}.crt}
  SUBJECT=$(openssl req -in $CSRFILE -subject -noout)
  [[ ${SUBJECT:0:8} == "subject=" ]] && SUBJECT=${SUBJECT:8} ||
    fatal "can't get subject in CSR '$CSRFILE'"
  SUBJECT=/${SUBJECT//, /\/}
  SUBJECT=${SUBJECT// = /=}
  COMMON_NAME=${SUBJECT##*/CN=}
  COMMON_NAME=${COMMON_NAME%%,*}
  create-crt "$CRTFILE"
}

#X-ACTION ca-update-crt CN|SUBJ|CRTFILE: upate certificate
function ca-update-crt() {
  local CRTFILE=${1:-$CRTFILE}
  local CSRFILE=${CSRFILE:-${CRTFILE%.crt}.csr}
  SUBJECT=$(openssl req -in "$CSRFILE" -subject -noout)
  [[ ${SUBJECT:0:8} == "subject=" ]] && SUBJECT=${SUBJECT:8} ||
    fatal "can't get subject in CSR '$CSRFILE'"
  yesno "Are you sure to update (revoke/sign) '$SUBJECT'" || return
  YES=1 ca-revoke-crt "$CRTFILE"
  YES=1 FORCE_CREATE_CRT=1 ca-sign-csr "$CSRFILE"
  return 0
}

#X-ACTION ca-revoke-crt CN|SUBJ|CRTFILE: revoke certificate
function ca-revoke-crt() {
  local CRTFILE=${1:-$CRTFILE}
  SUBJECT=$(openssl x509 -in $CRTFILE -subject -noout)
  [[ ${SUBJECT:0:8} == "subject=" ]] && SUBJECT=${SUBJECT:8} ||
    fatal "can't get subject in CRT '$CRTFILE'"
  SUBJECT=/${SUBJECT//, /\/}
  SUBJECT=${SUBJECT// = /=}
  COMMON_NAME=${SUBJECT##*/CN=}
  COMMON_NAME=${COMMON_NAME%%,*}
  yesno "Revoke certificate '$SUBJECT' ($CRTFILE)" || return

  PARAMS=(
    -config "$CA_CNFFILE"
    -batch
    -revoke "$CRTFILE"
    -gencrl
    ${CA_PASSWORD:+-passin env:CA_PASSWORD}
  )
  $OPENSSL ca "${PARAMS[@]}"
  is-error "can't revoke certificate '$SUBJECT'" || return
}

function usage() {
  local IFS=$'\t'
  exec >&2
  if [[ $0 == "-bash" ]] ; then return 1 ; fi
  [[ $# -gt 0 ]] && echo "ERROR: $*"
  version
  echo "Usage: ${0##*/} [options] ACTION [ACTION-PARAMETERS]"
  echo "Options:"
  sed -nr "s/^[[:space:]]*## ([^:]*): /\1\t/p" -- "$0" |
    while read OPT DESC ; do
      printf " %-20s %s\n" "$OPT" "$DESC"
    done
  echo
  echo "<ACTION> is one of :"
  sed -nr "s/^#X-ACTION ([^:]*): /\1\t/p" -- "$0" |
    while read OPT DESC ; do
      printf " %s\n     %s\n" "$OPT" "$DESC"
    done
  echo
  echo "For SubjAltName, add address type : DNS:<FQDN>, IP:ADDR"
  return 0
}

function version() {
  local PROGFILE=$0
  local VERSION=$(sed -n 's/^# Version: //p' $PROGFILE)
  local AUTHOR=$(sed -n 's/^# Author: //p' $PROGFILE)
  local LICENSE=$(sed -n 's/^# License: //p' $PROGFILE)

  echo "${PROGFILE##*/} $VERSION - $AUTHOR - $LICENSE"
}

declare OPENSSL=${ZPKI_OPENSSL:-openssl_debug}
declare BASEDIR=""
declare VERBOSE=1
declare XDEBUG=0

while (( $# > 0 )); do
  case "$1" in
    ## -h, --help: This help
    -h|--help) usage && exit 0 ;;
    ## -V, --version: Show version
    -V|--version) version && exit 0 ;;
    ## --x-debug: Enable bash debug mode
    --x-debug)    XDEBUG=1 ;;
    ## -v, --verbose: Define verbose level (must be repeat)
    -v|--verbose) ((VERBOSE++)) ;;
    ## -q, --quiet: Set verbose level to 0
    -q|--quiet) ((VERBOSE=0)) ;;
    ## -C, --ca: Set current CA base directory
    -C|--ca) BASEDIR=$2 ; shift ;;
    ## -Fcsr: Regenerate CSR even if exists (eg: change in SANs)
    -Fcsr) FORCE_CREATE_CSR=1 ;;
    ## -y, --yes: valid all response
    -y|--yes) YES=1 ;;
    ## -c, --cipher CIPHER: Define cipher for key (none for no encryption)
    -c|--cipher) CIPHER=$2 ; [[ $CIPHER == none ]] && unset CIPHER ; shift ;;
    # generic args
    --) shift ; break ;;
    -*) usage "Unknown parameter '$1'" && exit 1 ;;
    *) ARGS+=( "$1" ) ;;
  esac
  shift
done

[[ $XDEBUG == 1 ]] && set -x

[[ -z ${ARGS[@]} ]] &&
  fatal --usage "need ACTION"

ACTION=${ARGS[0]}; ARGS=( "${ARGS[@]:1}" )

declare -f "$ACTION" > /dev/null ||
  fatal "undefine action '$ACTION'"

####################################################
## main program starts here
####################################################

## FIXME - smart detection of action wanted

[[ $PASSWORD ]] && export PASSWORD
[[ $CA_PASSWORD ]] && export CA_PASSWORD

if [[ $BASEDIR ]]; then
  if [[ ! -d $BASEDIR ]]; then
    yesno "Create CA storage directory '$BASEDIR'" ||
      fatal "Can't create CA storage directory '$BASEDIR'"
    mkdir -p $BASEDIR
  fi
  cd $BASEDIR
fi

CA_KEYFILE=ca.key
CA_CRTFILE=ca.crt
CA_CNFFILE=ca.cnf

if [[ -r ${ARGS[0]} ]]; then
  # ARGV[0] is a filename
  FILENAME=${ARGV[0]}
elif [[ ${ARGS[0]} == "/" ]]; then
  # if ARGV[0] begin with /, it is a subject
  shopt -s nocasematch
  SUBJECT="${ARGS[0]}"
  COMMON_NAME="${SUBJECT##*/CN=}"
  [[ -z ${COMMON_NAME//[^/=]} ]] ||
    fatal "empty or bad Common Name"
elif [[ ${ARGS[0]} ]]; then
  # it's a non empty common name
  COMMON_NAME=${ARGS[0]}
  SUBJECT="/CN=$COMMON_NAME"
else
  unset COMMON_NAME
fi

if [[ $COMMON_NAME ]]; then
  # only read subj altnames if CN is already read
  for ((i=1;i<${#ARGS[@]};i++)) ; do
    SUBJALT="${SUBJALT:+$SUBJALT,}${ARGS[i]}"
  done
else
  $ACTION "${ARGS[@]}"
  exit $?
fi

if [[ $ACTION == create-cnf ]]; then
  create-cnf ${CNFFILE:-CA_CNFFILE}
  exit $?
elif [[ $ACTION == create-ca ]]; then
  SUBJECT=${SUBJECT:-"/CN=Certificate Authority"}
  create-ca
  exit $?
fi

if [[ ! -e $CA_CRTFILE ]]; then
  SUBJECT=${SUBJECT:-"/CN=Certificate Authority"} create-ca || exit $?
fi

[[ -z $FILENAME && $COMMON_NAME ]] && FILENAME=${COMMON_NAME//[^A-Za-z0-9@_-]/_}

if [[ -e $CA_CRTFILE ]]; then
  CNFFILE=${CNFFILE:-$CA_CNFFILE}
  KEYFILE=${KEYFILE:-private/$FILENAME.key}
  CRTFILE=${CRTFILE:-certs/$FILENAME.crt}
  CSRFILE=${CSRFILE:-certs/$FILENAME.csr}
else
  KEYFILE=${KEYFILE:-$FILENAME.key}
  CNFFILE=${CNFFILE:-$FILENAME.cnf}
  CRTFILE=${CRTFILE:-$FILENAME.crt}
  CSRFILE=${CSRFILE:-$FILENAME.csr}
fi

"$ACTION"
